# -*- coding: utf-8 -*-
"""ImageGenerationwithPre-trainedModels.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qY200Xj9EvEiGHCrucr2HB5LhZU4gE36
"""

!pip install diffusers transformers torch

from huggingface_hub import login
from diffusers import StableDiffusionPipeline
import torch
from PIL import Image
import io
from IPython.display import display

login(token="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")


pipe = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2", use_auth_token=True)


pipe = pipe.to("cuda")


prompt = "A beautiful sunset over a mountain range"


image = pipe(prompt).images[0]

display(image)
-

from huggingface_hub import login
from diffusers import StableDiffusionPipeline
import torch
from PIL import Image
from IPython.display import display

login(token="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")

pipe = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2", use_auth_token=True)


pipe = pipe.to("cuda")

prompt = input("Enter your prompt: ")


image = pipe(prompt).images[0]


display(image)